version: $(appveyor_repo_tag_name)
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
before_build:
- ps: dotnet restore
build:
  project: dotNetCiCdTest.sln
  verbosity: minimal
test_script:
- cmd: >-
    dotnet test dotNetCiCdTest.Tests/dotNetCiCdTest.Tests.csproj

    dotnet pack dotNetCiCdTest/dotNetCiCdTest.csproj --configuration Release
artifacts:
- path: dotNetCiCdTest/bin/Release/AppLogger.dotNetCiCdTest.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: fkik3XGPWwOjxaLG1W/cPSPU2tGlfo6E3E+sQPsAPOzXq92WlaNrHawiKbN8JfOa
  on:
    appveyor_repo_tag: true